# Generated by Django 3.2.9 on 2022-11-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0004_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ssh_port',
            field=models.IntegerField(default=255),
        ),
    ]
