# Generated by Django 3.2.9 on 2022-11-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0006_alter_device_ssh_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
