# Generated by Django 3.2.9 on 2022-11-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0010_alter_device_ssh_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ssh_port',
        ),
    ]
